### ISSUE TITLE
Missing `#define SS`

### ISSUE THREAD

**Issue by zfields** [ms-iot/lightning#18]
Spi.h on Arduino supplies a constant `SS`, which allows code that uses SPI to be portable across Arduino boards and compatibles (like Windows DMAP for example).

**Comment by MahmoudGSaleh** [comment]
We've chip select, CS0 and CS1 in Raspberry PI and CS0 in MBM defined in pins_arduino.h. I guess we could define SS as CS0 as well to make the code portable.

**Comment by MahmoudGSaleh** [comment]
Fixed in #37
