### ISSUE TITLE
Need avr/pgmspace.h variables

### ISSUE THREAD

**Issue by zfields** [ms-iot/lightning#21]
Discovered due to:
Need to define and map `uint_farptr_t` to `const char *`

Look here for all types:
http://www.nongnu.org/avr-libc/user-manual/group__avr__pgmspace.html

**Comment by MahmoudGSaleh** [comment]
Thanks! The next iteration will have many of these types.

**Comment by MahmoudGSaleh** [comment]
Fixed in #37
