### ISSUE TITLE
#define PROGMEM

### ISSUE THREAD

**Issue by sidwarkd** [ms-iot/lightning#23]
The PROGMEM keyword is only defined in AVR contexts but needs to exist in Lightning so existing Arduino examples will work.

`#define PROGMEM`
Add to [pgmspace.h](../blob/master/source/avr/pgmspace.h)

**Comment by ooeygui** [comment]
Assigning to Mahmoud

**Comment by ooeygui** [comment]
Wrong assignment

**Comment by MahmoudGSaleh** [comment]
Thanks! Will fix it for the next iteration of the SDK updates.

**Comment by MahmoudGSaleh** [comment]
Fixed in #37
