### ISSUE TITLE
Performance Document Refresh

### ISSUE THREAD

**Issue by johnkattenhorn** [ms-iot/lightning#42]
I was looking at the performance document I found here

https://raw.githubusercontent.com/ms-iot/content/develop/en-US/Docs/LightningPerformance.md

They look kind of old so I was searching for the code which generated them and can't find it to run them against the latest bits.

Could the performance statistics be refreshed or the code release to allow us to do it ?

**Comment by IoTGirl** [comment]
Hi John,
An item has been added to the IoT Core backlog collect these numbers again on the next refresh. See [https://github.com/ms-iot/content/issues/1042](https://github.com/ms-iot/content/issues/1042 )as well.
Sincerely, IoTGirl
