### ISSUE TITLE
The ValueChanged-event of a GPIO Pin with MinnowBoard MAX not working

### ISSUE THREAD

**Issue by SaschaIoT** [ms-iot/lightning#47]
Hello together,

the ValueChanged event of a GPIO Pin gets never called using the lightning providers with MinnowBoard MAX.

Is the ValueChanged event still not supported with MinnowBoard MAX and Windows IoT Core 15063.0?

LowLevelDevicesController.DefaultProvider = LightningProvider.GetAggregateProvider();
var gpioController = GpioController.GetDefault();
var pin = gpioController.OpenPin(0);
pin.SetDriveMode(GpioPinDriveMode.Input);
pin.ValueChanged += (gpioPin, args) =>
{
//Gets never called
};

**Comment by SaschaIoT** [comment]
Here some additional informations.

I am using a C# UWP app with following references:

Windows Desktop Extensions for the UWP 15063
Windows IoT Extensions for the UWP 15063

and the NuGet library:

Microsoft.IoT.Lightning latest stable 1.1.0

I use the new MinnowBoard Turbot Quad Core with:
Windows IoT Core 15063.0

Thanks and best regards
Sascha

**Comment by SaschaIoT** [comment]
The ValueChanged event is working with Raspberry Pi 3 Model B and Windows IoT Core 15063 without any problems. So I guess it is a bug in the library in combination with the MinnowBoard.

**Comment by matt1va** [comment]
This should be fixed with PR #52

**Comment by MahmoudGSaleh** [comment]
Thanks @matt1va for submitting the fix. Closing now.
