### ISSUE TITLE
DMAP error -  interface specification -- where is it?

### ISSUE THREAD

**Issue by HattonLe** [ms-iot/lightning#55]
Where can I find the source code for the Microsoft Bus Driver that implements the DMAP capability?
or alternatively where the DMAP interface protocol is defined?
I have an error DMAP_E_INVALID_LOCK_HANDLE_SPECIFIED when attempting to attach an interupt to a GPIO pin and can't figure out what is missing to cause it.

**Comment by saraclay** [comment]
Hello, because we are no longer monitoring this repo, could you please file this issue at: https://github.com/MicrosoftDocs/windows-iotcore-docs
