### ISSUE TITLE
Raspberry Pi Gpio Input Modes

### ISSUE THREAD

**Issue by DhruvKoolRajamani** [ms-iot/lightning#59]
Hi, after going through the repository, I was unable to find the implementation of the InputPullDown mode offered by most controllers. Is there any chance to implement this for the Pi?

Windows.Devices.Gpio Drive Mode Reference:
https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiopindrivemode

**Comment by jordanrh1** [comment]
InputPullDown is supported by the inbox driver. Lightning is no longer being maintained.

**Comment by DjArt** [comment]
So how to use PWM & PullDown at the same time?

**Comment by DjArt** [comment]
https://github.com/DjArt/lightning/commit/64902d36e80b58a3c4ac1554da2fefdfa15def46 Fixed
