### ISSUE TITLE
Raspberry Pi PWM

### ISSUE THREAD

**Issue by DjArt** [ms-iot/lightning#60]
Pins 2 & 3 not able to use as PWM. Initialization fails with SEHException.

**Comment by saraclay** [comment]
Thank you for the feedback. Please file this as a bug using Feedback Hub if this is a blocker for you: https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT
